# Generated by Django 4.0.2 on 2023-04-08 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCardPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=15)),
                ('transact_id', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('message', models.TextField(max_length=200)),
                ('currency', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
                ('created', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
