# Generated by Django 4.0.2 on 2023-04-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_quizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizes',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
