# Generated by Django 4.0.2 on 2023-04-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_quizes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizes',
            name='answered_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
