# Generated by Django 4.0.2 on 2023-04-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_quizes_answered_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('quiz', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
