# Generated by Django 4.0.2 on 2023-04-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_mails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='location',
            field=models.CharField(default='Kenya,Nakuru,njoro', max_length=50),
            preserve_default=False,
        ),
    ]
