# Generated by Django 4.0.2 on 2023-04-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_stripecardpayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecardpayments',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
