# Generated by Django 4.0.2 on 2023-04-08 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('quiz', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.TextField(max_length=100)),
                ('answer', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('answered_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
